from sqlalchemy import Column, Integer, String, DateTime, Boolean, Float, Text, ForeignKey
from sqlalchemy.orm import relationship
from app.core.database import Base

class PA_DI_FA(Base):
    __tablename__ = 'pa_di_fa'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    evento = Column(String, )
    resuelto = Column(Boolean, nullable=False)
    

class PA_DI_PR(Base):
    __tablename__ = 'pa_di_pr'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    codigo_del_proceso = Column(String, )
    proceso = Column(String, )
    vigente = Column(Boolean, nullable=False)
    

class PA_DI_RA(Base):
    __tablename__ = 'pa_di_ra'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    fecha_de_apertura = Column(DateTime, )
    registrado_por = Column(String, )
    origen_de_documento = Column(String, )
    tipo_de_documento = Column(String, )
    proceso = Column(Integer, )
    codigo_de_documento_global = Column('codigo_de_documento_global', String, )
    codigo_particular = Column(String, )
    documento = Column(String, )
    revisado_por = Column(String, )
    modificaciones = Column(String, )
    numerales_afectados = Column(String, )
    observaciones = Column(String, )
    aprobado_por = Column(String, )
    version_nueva = Column(String, )
    aprobado = Column(Boolean, nullable=False)
    aplica_comprobacion = Column(Boolean, nullable=False)
    comentarios_de_comprobacion = Column(String, )
    comprobado = Column(Boolean, nullable=False)
    ubicacion = Column(String, )
    fecha_de_cierre = Column(DateTime, )
    

class PA_EQ_AC(Base):
    __tablename__ = 'pa_eq_ac'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, nullable=False)
    actividad = Column(String, primary_key=True, nullable=False)
    descripción = Column(String, )
    

class PA_EQ_CA(Base):
    __tablename__ = 'pa_eq_ca'
    __table_args__ = {'schema': 'SGApp'}
    id_equi = Column(Integer, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    equipamiento = Column(String, )
    certificado = Column(String, primary_key=True, nullable=False)
    ente_calibrador = Column(String, )
    fecha_de_calibracion = Column(DateTime, )
    unidades = Column(String, )
    observaciones = Column(String, )
    apto = Column(Boolean, nullable=False)
    regla = Column(String, )

    pa_eq_dc_items = relationship('PA_EQ_DC', back_populates='pa_eq_ca_rel')
    pa_eq_ex_items = relationship('PA_EQ_EX', back_populates='pa_eq_ca_rel')
    pa_eq_hm_items = relationship('PA_EQ_HM', back_populates='pa_eq_ca_rel')
    pa_eq_rp_items = relationship('PA_EQ_RP', back_populates='pa_eq_ca_rel')

class PA_EQ_CB(Base):
    __tablename__ = 'pa_eq_cb'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_ci = Column(Integer, )
    tipoprueba = Column(String, )
    pesapatron_id = Column(String, )
    posicion = Column(String, )
    lectura_balanza = Column(Float, )
    lectura_corregida = Column(Float, )

class PA_EQ_CH(Base):
    __tablename__ = 'pa_eq_ch'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_ci = Column(Integer, )
    posicion = Column(String, )
    temppatron_leida = Column(Float, )
    tempequipo_leida = Column(Float, )
    diferencia = Column(Float, )
    resultadopunto = Column(String, )

class PA_EQ_CI(Base):
    __tablename__ = 'pa_eq_ci'
    __table_args__ = {'schema': 'SGApp'}
    id_equi = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    equipamiento = Column(String, )
    balanza_utilizada = Column(String, )
    unidades = Column(String, )
    observaciones = Column(String, )
    promedio = Column(Float, )
    desv_est = Column(Float, )
    tol_sistematico = Column(Float, )
    conclusion_sistematico = Column(String, )
    temperatura = Column(Float, )
    lugar = Column(String, )
    presion_hpa = Column(Float, )
    humedad_relativa = Column(Float, )
    en = Column(Float, )
    conclusion_en = Column(String, )
    volumen_nominal = Column(Float, )
    valor = Column(Float, )
    incertidumbre = Column(Float, )
    tipo_comprobacion = Column(String, )
    tempprogramada = Column(Float, )
    termometro_id = Column(String, )
    cg = Column(Float, )
    cgk = Column(Float, )


class PA_EQ_CV(Base):
    __tablename__ = 'pa_eq_cv'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_ci = Column(Integer, )
    matraz_vacio = Column(Float, )
    corr1 = Column(Float, )
    matraz_lleno = Column(Float, )
    corr2 = Column(Float, )
    masa_h2o = Column(Float, )
    densidad = Column(Float, )
    volumen = Column(Float, )

class PA_EQ_DC(Base):
    __tablename__ = 'pa_eq_dc'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_ca = Column(String, ForeignKey('SGApp.pa_eq_ca.certificado'))
    valor_nominal = Column(Float, )
    referencia = Column(String, )
    correccion_reportada = Column(Float, )
    incertidumbre = Column(Float, )
    tolerancia_de_medicion = Column(Float, )
    conformidad = Column(String, )
    
    pa_eq_ca_rel = relationship('PA_EQ_CA', back_populates='pa_eq_dc_items')

class PA_EQ_EQ(Base):
    __tablename__ = 'pa_eq_eq'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    equipamiento = Column(String, )
    código_interno = Column(String, nullable=False)
    marca = Column(String, )
    serie = Column(String, )
    material = Column(String, )
    numero_de_piezas = Column(String, )
    max_vn = Column(String, )
    d = Column(String, )
    clase_de_exactitud = Column(String, )
    ubicacion = Column(String, )
    comentarios = Column(String, )
    puesta_en_funcionamiento = Column(DateTime, )
    estado = Column(String, )
    requiere = Column(String, )
    frecuencia_de_calibracion = Column(String, )
    frecuencia_de_mantenimiento = Column(String, )
    frecuencia_de_comprobacion_intermedia = Column(String, )
    frecuencia_de_calificacion = Column(String, )

class PA_EQ_EX(Base):
    __tablename__ = 'pa_eq_ex'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_ca = Column(String, ForeignKey('SGApp.pa_eq_ca.certificado'))
    carga = Column(Float, )
    posicion = Column(Float, )
    diferencia_reportada = Column(Float, )
    tolerancia = Column(Float, )
    conformidad = Column(String, )
    
    pa_eq_ca_rel = relationship('PA_EQ_CA', back_populates='pa_eq_ex_items')

class PA_EQ_HM(Base):
    __tablename__ = 'pa_eq_hm'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_ca = Column(String, ForeignKey('SGApp.pa_eq_ca.certificado'))
    temperatura_nominal = Column(Float, )
    en_el_tiempo = Column(Float, )
    incertidumbre_expandida = Column(Float, )
    tolerancia_en_el_tiempo = Column(Float, )
    conformidad_tiempo = Column(String, )
    en_el_espacio = Column(Float, )
    tolerancia_en_el_espacio = Column(Float, )
    conformidad_espacio = Column(String, )
    
    pa_eq_ca_rel = relationship('PA_EQ_CA', back_populates='pa_eq_hm_items')

class PA_EQ_LE(Base):
    __tablename__ = 'pa_eq_le'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, nullable=False)
    lista_de_equipos = Column(String, primary_key=True, nullable=False)
    

class PA_EQ_MA(Base):
    __tablename__ = 'pa_eq_ma'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column('registrado-por', String, )
    fecha = Column(DateTime, )
    equipamiento = Column(String, )
    tipo_de_mantenimiento = Column(String, )
    comentarios_de_mantenimiento = Column(String, )
    apto = Column(Boolean, nullable=False)
    

class PA_EQ_MO(Base):
    __tablename__ = 'pa_eq_mo'
    __table_args__ = {'schema': 'SGApp'}
    id_movimiento = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, ForeignKey('SGApp.pa_pe_pe.abreviatura')) 
    id_reactivo = Column(Integer, ForeignKey('SGApp.pa_eq_re.id_reactivo'))
    fecha_movimiento = Column(DateTime, )
    tipo_movimiento = Column(String, )
    cantidad = Column(Float, )
    saldo = Column(Float, )
    id_adquisicion = Column(Integer, )
    registrado_por = Column(String, ForeignKey('SGApp.pa_pe_pe.abreviatura'))
    observaciones = Column(String, )
    
    pa_eq_re_rel = relationship('PA_EQ_RE', back_populates='pa_eq_mo_items')
    pa_pe_pe_rel = relationship('PA_PE_PE', back_populates='pa_eq_mo_items')
    registrado_por_obj = relationship("PA_PE_PE", foreign_keys=[registrado_por])

class PA_EQ_MR(Base):
    __tablename__ = 'pa_eq_mr'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    equipamiento = Column(String, )
    código_interno = Column(String, nullable=False)
    tipo = Column(String, )
    certificado = Column(String, )
    fecha_de_certificado = Column(DateTime, )
    codigo_original = Column(String, )
    productor_del_material_de_referencia = Column(String, )
    procedencia = Column(String, )
    serie = Column(String, )
    material = Column(String, )
    ubicacion = Column(String, )
    comentarios = Column(String, )
    fecha_de_apertura = Column(DateTime, )
    fecha_de_vencimiento = Column(DateTime, )
    estado = Column(String, )
    # trial814 = Column(String, )

class PA_EQ_MV(Base):
    __tablename__ = 'pa_eq_mv'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_mr = Column(String, )
    parametro = Column(String, )
    valor = Column(Float, )
    incertidumbre = Column(Float, )
    unidad = Column(String, )
    # trial817 = Column(String, )

class PA_EQ_PA(Base):
    __tablename__ = 'pa_eq_pa'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    gestión = Column(String, )
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    comentarios = Column(String, )
    # trial817 = Column(String, )

class PA_EQ_PR(Base):
    __tablename__ = 'pa_eq_pr'
    __table_args__ = {'schema': 'SGApp'}
    id_prog = Column(Integer, primary_key=True, nullable=False)
    id_pa = Column(Integer, )
    mes = Column(String, )
    actividad = Column(String, )
    equipamiento = Column(String, )
    realizado = Column(Boolean, nullable=False)
    anulado = Column(Boolean, nullable=False)
    comentarios = Column(String, )
    # trial817 = Column(String, )

class PA_EQ_RE(Base):
    __tablename__ = 'pa_eq_re'
    __table_args__ = {'schema': 'SGApp'}
    id_reactivo = Column(Integer, primary_key=True, nullable=False)
    nombre_reactivo = Column(String, )
    proveedor = Column(String, )
    unidad_almacen = Column(String, )
    stock_minimo = Column(Integer, )
    ubicacion = Column(String, )
    marca = Column(String, )
    serie = Column(String, )
    codigo_interno = Column(String, )
    no_articulo = Column(String, )
    valor = Column(Float, )
    unidad = Column(String, )
    grado_calidad = Column(String, )
    estado = Column(String, )
    fecha_de_apertura = Column(DateTime, )
    fecha_de_vencimiento = Column(DateTime, )
    sustancia_controlada = Column(Boolean, nullable=False)
    comentarios = Column(String, )
    # trial814 = Column(String, )
    pa_eq_mo_items = relationship('PA_EQ_MO', back_populates='pa_eq_re_rel')

class PA_EQ_RP(Base):
    __tablename__ = 'pa_eq_rp'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_ca = Column(String, ForeignKey('SGApp.pa_eq_ca.certificado'))
    carga = Column(Float, )
    desv_est = Column(Float, )
    tolerancia = Column(Float, )
    conformidad = Column(String, )
    # trial817 = Column(String, )
    pa_eq_ca_rel = relationship('PA_EQ_CA', back_populates='pa_eq_rp_items')

class PA_EQ_VE(Base):
    __tablename__ = 'pa_eq_ve'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    fecha = Column(DateTime, )
    registrado_por = Column(String, )
    set_patrón = Column(String, )
    set_comparado = Column(String, )
    objeto_ítem_medio = Column(String, )
    ítem_1 = Column(String, )
    res_patrón_1 = Column(Float, )
    u_patrón_1 = Column(Float, )
    res_comparado_1 = Column(Float, )
    u_comparado_1 = Column(Float, )
    en_1 = Column(Float, )
    ítem_2 = Column(String, )
    res_patrón_2 = Column(Float, )
    u_patrón_2 = Column(Float, )
    res_comparado_2 = Column(Float, )
    u_comparado_2 = Column(Float, )
    en_2 = Column(Float, )
    ítem_3 = Column(String, )
    res_patrón_3 = Column(Float, )
    u_patrón_3 = Column(Float, )
    res_comparado_3 = Column(Float, )
    u_comparado_3 = Column(Float, )
    en_3 = Column(Float, )
    ítem_4 = Column(String, )
    res_patrón_4 = Column(Float, )
    u_patrón_4 = Column(Float, )
    res_comparado_4 = Column(Float, )
    u_comparado_4 = Column(Float, )
    en_4 = Column(Float, )
    ítem_5 = Column(String, )
    res_patrón_5 = Column(Float, )
    u_patrón_5 = Column(Float, )
    res_comparado_5 = Column(Float, )
    u_comparado_5 = Column(Float, )
    en_5 = Column(Float, )
    ítem_6 = Column(String, )
    res_patrón_6 = Column(Float, )
    u_patrón_6 = Column(Float, )
    res_comparado_6 = Column(Float, )
    u_comparado_6 = Column(Float, )
    en_6 = Column(Float, )
    ítem_7 = Column(String, )
    res_patrón_7 = Column(Float, )
    u_patrón_7 = Column(Float, )
    res_comparado_7 = Column(Float, )
    u_comparado_7 = Column(Float, )
    en_7 = Column(Float, )
    ítem_8 = Column(String, )
    res_patrón_8 = Column(Float, )
    u_patrón_8 = Column(Float, )
    res_comparado_8 = Column(Float, )
    u_comparado_8 = Column(Float, )
    en_8 = Column(Float, )
    ítem_9 = Column(String, )
    res_patrón_9 = Column(Float, )
    u_patrón_9 = Column(Float, )
    res_comparado_9 = Column(Float, )
    u_comparado_9 = Column(Float, )
    en_9 = Column(Float, )
    ítem_10 = Column(String, )
    res_patrón_10 = Column(Float, )
    u_patrón_10 = Column(Float, )
    res_comparado_10 = Column(Float, )
    u_comparado_10 = Column(Float, )
    en_10 = Column(Float, )
    ítem_11 = Column(String, )
    res_patrón_11 = Column(Float, )
    u_patrón_11 = Column(Float, )
    res_comparado_11 = Column(Float, )
    u_comparado_11 = Column(Float, )
    en_11 = Column(Float, )
    ítem_12 = Column(String, )
    res_patrón_12 = Column(Float, )
    u_patrón_12 = Column(Float, )
    res_comparado_12 = Column(Float, )
    u_comparado_12 = Column(Float, )
    en_12 = Column(Float, )
    ítem_13 = Column(String, )
    res_patrón_13 = Column(Float, )
    u_patrón_13 = Column(Float, )
    res_comparado_13 = Column(Float, )
    u_comparado_13 = Column(Float, )
    en_13 = Column(Float, )
    ítem_14 = Column(String, )
    res_patrón_14 = Column(Float, )
    u_patrón_14 = Column(Float, )
    res_comparado_14 = Column(Float, )
    u_comparado_14 = Column(Float, )
    en_14 = Column(Float, )
    ítem_15 = Column(String, )
    res_patrón_15 = Column(Float, )
    u_patrón_15 = Column(Float, )
    res_comparado_15 = Column(Float, )
    u_comparado_15 = Column(Float, )
    en_15 = Column(Float, )
    ítem_16 = Column(String, )
    res_patrón_16 = Column(Float, )
    u_patrón_16 = Column(Float, )
    res_comparado_16 = Column(Float, )
    u_comparado_16 = Column(Float, )
    en_16 = Column(Float, )
    ítem_17 = Column(String, )
    res_patrón_17 = Column(Float, )
    u_patrón_17 = Column(Float, )
    res_comparado_17 = Column(Float, )
    u_comparado_17 = Column(Float, )
    en_17 = Column(Float, )
    ítem_18 = Column(String, )
    res_patrón_18 = Column(Float, )
    u_patrón_18 = Column(Float, )
    res_comparado_18 = Column(Float, )
    u_comparado_18 = Column(Float, )
    en_18 = Column(Float, )
    ítem_19 = Column(String, )
    res_patrón_19 = Column(Float, )
    u_patrón_19 = Column(Float, )
    res_comparado_19 = Column(Float, )
    u_comparado_19 = Column(Float, )
    en_19 = Column(Float, )
    ítem_20 = Column(String, )
    res_patrón_20 = Column(Float, )
    u_patrón_20 = Column(Float, )
    res_comparado_20 = Column(Float, )
    u_comparado_20 = Column(Float, )
    en_20 = Column(Float, )
    ítem_21 = Column(String, )
    res_patrón_21 = Column(Float, )
    u_patrón_21 = Column(Float, )
    res_comparado_21 = Column(Float, )
    u_comparado_21 = Column(Float, )
    en_21 = Column(Float, )
    ítem_22 = Column(String, )
    res_patrón_22 = Column(Float, )
    u_patrón_22 = Column(Float, )
    res_comparado_22 = Column(Float, )
    u_comparado_22 = Column(Float, )
    en_22 = Column(Float, )
    ítem_23 = Column(String, )
    res_patrón_23 = Column(Float, )
    u_patrón_23 = Column(Float, )
    res_comparado_23 = Column(Float, )
    u_comparado_23 = Column(Float, )
    en_23 = Column(Float, )
    ítem_24 = Column(String, )
    res_patrón_24 = Column(Float, )
    u_patrón_24 = Column(Float, )
    res_comparado_24 = Column(Float, )
    u_comparado_24 = Column(Float, )
    en_24 = Column(Float, )
    ítem_25 = Column(String, )
    res_patrón_25 = Column(Float, )
    u_patrón_25 = Column(Float, )
    res_comparado_25 = Column(Float, )
    u_comparado_25 = Column(Float, )
    en_25 = Column(Float, )
    conclusión = Column(String, )
    observaciones = Column(String, )
    # trial817 = Column(String, )

class PA_IA_AH(Base):
    __tablename__ = 'pa_ia_ah'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_am = Column(Integer, ForeignKey('SGApp.pa_ia_am.id'))
    registrado_por = Column(String, )
    servicio = Column(String, )
    til = Column(Float, )
    hil = Column(Float, )
    fecha_y_hora_inicio = Column(DateTime, )
    ti = Column(Float, )
    hi = Column(Float, )
    tfl = Column(Float, )
    hfl = Column(Float, )
    fecha_y_hora_final = Column(DateTime, )
    tf = Column(Float, )
    hf = Column(Float, )
    delta_t = Column(Float, )
    delta_h = Column(Float, )
    aceptado_t = Column(String, )
    aceptado_h = Column(String, )
    comentario = Column(String, )
    # trial817 = Column(String, )
    pa_ia_am_rel = relationship('PA_IA_AM', back_populates='pa_ia_ah_items')

class PA_IA_AM(Base):
    __tablename__ = 'pa_ia_am'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    area = Column(Integer, ForeignKey('SGApp.pa_ia_ar.id'))
    instrumento = Column(String, )
    tmin = Column(Float, )
    tmax = Column(Float, )
    hmin = Column(Float, )
    hmax = Column(Float, )
    delta_t_max = Column(Float, )
    delta_h_max = Column(Float, )
    # trial817 = Column(String, )
    pa_ia_ah_items = relationship('PA_IA_AH', back_populates='pa_ia_am_rel')
    pa_ia_ar_rel = relationship('PA_IA_AR', back_populates='pa_ia_am_items')

class PA_IA_AR(Base):
    __tablename__ = 'pa_ia_ar'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    area = Column(String, )
    # trial817 = Column(String, )
    pa_ia_am_items = relationship('PA_IA_AM', back_populates='pa_ia_ar_rel')

class PA_IA_CA(Base):
    __tablename__ = 'pa_ia_ca'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    instalacion_condicion_ambiental = Column(String, )
    elemento = Column(String, )
    descripcion_del_control = Column(String, )
    control_eficaz = Column(Boolean, nullable=False)
    # trial817 = Column(String, )

class PA_IA_LE(Base):
    __tablename__ = 'pa_ia_le'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_li = Column(Integer, )
    area = Column(String, )
    que = Column(String, )
    frecuencia = Column(String, )
    como = Column(String, )
    D1 = Column(String, )
    D2 = Column(String, )
    D3 = Column(String, )
    D4 = Column(String, )
    D5 = Column(String, )
    D6 = Column(String, )
    D7 = Column(String, )
    D8 = Column(String, )
    D9 = Column(String, )
    D10 = Column(String, )
    D11 = Column(String, )
    D12 = Column(String, )
    D13 = Column(String, )
    D14 = Column(String, )
    D15 = Column(String, )
    D16 = Column(String, )
    D17 = Column(String, )
    D18 = Column(String, )
    D19 = Column(String, )
    D20 = Column(String, )
    D21 = Column(String, )
    D22 = Column(String, )
    D23 = Column(String, )
    D24 = Column(String, )
    D25 = Column(String, )
    D26 = Column(String, )
    D27 = Column(String, )
    D28 = Column(String, )
    D29 = Column(String, )
    D30 = Column(String, )
    D31 = Column(String, )
    # trial817 = Column(String, )

class PA_IA_LI(Base):
    __tablename__ = 'pa_ia_li'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    año = Column(String, )
    mes = Column(String, )
    fecha = Column(DateTime, )
    comentarios = Column(String, )
    # trial817 = Column(String, )

class PA_IA_RA(Base):
    __tablename__ = 'pa_ia_ra'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    vigente = Column(Boolean, nullable=False)
    instalacion = Column(String, )
    actividad_que_se_realizara = Column(String, )
    comentario = Column(String, )
    item_de_ca_1 = Column(String, )
    requisito_1 = Column(String, )
    item_de_ca_2 = Column(String, )
    requisito_2 = Column(String, )
    item_de_ca_3 = Column(String, )
    requisito_3 = Column(String, )
    item_de_ca_4 = Column(String, )
    requisito_4 = Column(String, )
    item_de_ca_5 = Column(String, )
    requisito_5 = Column(String, )
    item_de_ca_6 = Column(String, )
    requisito_6 = Column(String, )
    item_de_ca_7 = Column(String, )
    requisito_7 = Column(String, )
    item_de_ca_8 = Column(String, )
    requisito_8 = Column(String, )
    item_de_ca_9 = Column(String, )
    requisito_9 = Column(String, )
    item_de_ca_10 = Column(String, )
    requisito_10 = Column(String, )
    item_de_ca_11 = Column(String, )
    requisito_11 = Column(String, )
    item_de_ca_12 = Column(String, )
    requisito_12 = Column(String, )
    item_de_ca_13 = Column(String, )
    requisito_13 = Column(String, )
    item_de_ca_14 = Column(String, )
    requisito_14 = Column(String, )
    item_de_ca_15 = Column(String, )
    requisito_15 = Column(String, )
    item_de_ca_16 = Column(String, )
    requisito_16 = Column(String, )
    item_de_ca_17 = Column(String, )
    requisito_17 = Column(String, )
    item_de_ca_18 = Column(String, )
    requisito_18 = Column(String, )
    item_de_ca_19 = Column(String, )
    requisito_19 = Column(String, )
    item_de_ca_20 = Column(String, )
    requisito_20 = Column(String, )
    # trial817 = Column(String, )

class PA_IA_RI(Base):
    __tablename__ = 'pa_ia_ri'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    vigente = Column(Boolean, nullable=False)
    instalacion = Column(String, )
    actividad_que_se_realizara = Column(String, )
    comentario = Column(String, )
    item_de_instalacion_1 = Column(String, )
    requisito_1 = Column(String, )
    item_de_instalacion_2 = Column(String, )
    requisito_2 = Column(String, )
    item_de_instalacion_3 = Column(String, )
    requisito_3 = Column(String, )
    item_de_instalacion_4 = Column(String, )
    requisito_4 = Column(String, )
    item_de_instalacion_5 = Column(String, )
    requisito_5 = Column(String, )
    item_de_instalacion_6 = Column(String, )
    requisito_6 = Column(String, )
    item_de_instalacion_7 = Column(String, )
    requisito_7 = Column(String, )
    item_de_instalacion_8 = Column(String, )
    requisito_8 = Column(String, )
    item_de_instalacion_9 = Column(String, )
    requisito_9 = Column(String, )
    item_de_instalacion_10 = Column(String, )
    requisito_10 = Column(String, )
    item_de_instalacion_11 = Column(String, )
    requisito_11 = Column(String, )
    item_de_instalacion_12 = Column(String, )
    requisito_12 = Column(String, )
    item_de_instalacion_13 = Column(String, )
    requisito_13 = Column(String, )
    item_de_instalacion_14 = Column(String, )
    requisito_14 = Column(String, )
    item_de_instalacion_15 = Column(String, )
    requisito_15 = Column(String, )
    item_de_instalacion_16 = Column(String, )
    requisito_16 = Column(String, )
    item_de_instalacion_17 = Column(String, )
    requisito_17 = Column(String, )
    item_de_instalacion_18 = Column(String, )
    requisito_18 = Column(String, )
    item_de_instalacion_19 = Column(String, )
    requisito_19 = Column(String, )
    item_de_instalacion_20 = Column(String, )
    requisito_20 = Column(String, )
    # trial820 = Column(String, )

class PA_IA_SA(Base):
    __tablename__ = 'pa_ia_sa'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    id_requisitos_condiciones_ambientales = Column(Integer, )
    comentario = Column(String, )
    requiere_acciones = Column(Boolean, nullable=False)
    evaluacion_requisito_1 = Column(String, )
    conforme_1 = Column(Boolean, nullable=False)
    evaluacion_requisito_2 = Column(String, )
    conforme_2 = Column(Boolean, nullable=False)
    evaluacion_requisito_3 = Column(String, )
    conforme_3 = Column(Boolean, nullable=False)
    evaluacion_requisito_4 = Column(String, )
    conforme_4 = Column(Boolean, nullable=False)
    evaluacion_requisito_5 = Column(String, )
    conforme_5 = Column(Boolean, nullable=False)
    evaluacion_requisito_6 = Column(String, )
    conforme_6 = Column(Boolean, nullable=False)
    evaluacion_requisito_7 = Column(String, )
    conforme_7 = Column(Boolean, nullable=False)
    evaluacion_requisito_8 = Column(String, )
    conforme_8 = Column(Boolean, nullable=False)
    evaluacion_requisito_9 = Column(String, )
    conforme_9 = Column(Boolean, nullable=False)
    evaluacion_requisito_10 = Column(String, )
    conforme_10 = Column(Boolean, nullable=False)
    evaluacion_requisito_11 = Column(String, )
    conforme_11 = Column(Boolean, nullable=False)
    evaluacion_requisito_12 = Column(String, )
    conforme_12 = Column(Boolean, nullable=False)
    evaluacion_requisito_13 = Column(String, )
    conforme_13 = Column(Boolean, nullable=False)
    evaluacion_requisito_14 = Column(String, )
    conforme_14 = Column(Boolean, nullable=False)
    evaluacion_requisito_15 = Column(String, )
    conforme_15 = Column(Boolean, nullable=False)
    evaluacion_requisito_16 = Column(String, )
    conforme_16 = Column(Boolean, nullable=False)
    evaluacion_requisito_17 = Column(String, )
    conforme_17 = Column(Boolean, nullable=False)
    evaluacion_requisito_18 = Column(String, )
    conforme_18 = Column(Boolean, nullable=False)
    evaluacion_requisito_19 = Column(String, )
    conforme_19 = Column(Boolean, nullable=False)
    evaluacion_requisito_20 = Column(String, )
    conforme_20 = Column(Boolean, nullable=False)
    # trial820 = Column(String, )

class PA_IA_SI(Base):
    __tablename__ = 'pa_ia_si'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    id_requisitos_de_instalacion = Column(Integer, )
    comentario = Column(String, )
    requiere_acciones = Column(Boolean, nullable=False)
    evaluacion_requisito_1 = Column(String, )
    conforme_1 = Column(Boolean, nullable=False)
    evaluacion_requisito_2 = Column(String, )
    conforme_2 = Column(Boolean, nullable=False)
    evaluacion_requisito_3 = Column(String, )
    conforme_3 = Column(Boolean, nullable=False)
    evaluacion_requisito_4 = Column(String, )
    conforme_4 = Column(Boolean, nullable=False)
    evaluacion_requisito_5 = Column(String, )
    conforme_5 = Column(Boolean, nullable=False)
    evaluacion_requisito_6 = Column(String, )
    conforme_6 = Column(Boolean, nullable=False)
    evaluacion_requisito_7 = Column(String, )
    conforme_7 = Column(Boolean, nullable=False)
    evaluacion_requisito_8 = Column(String, )
    conforme_8 = Column(Boolean, nullable=False)
    evaluacion_requisito_9 = Column(String, )
    conforme_9 = Column(Boolean, nullable=False)
    evaluacion_requisito_10 = Column(String, )
    conforme_10 = Column(Boolean, nullable=False)
    evaluacion_requisito_11 = Column(String, )
    conforme_11 = Column(Boolean, nullable=False)
    evaluacion_requisito_12 = Column(String, )
    conforme_12 = Column(Boolean, nullable=False)
    evaluacion_requisito_13 = Column(String, )
    conforme_13 = Column(Boolean, nullable=False)
    evaluacion_requisito_14 = Column(String, )
    conforme_14 = Column(Boolean, nullable=False)
    evaluacion_requisito_15 = Column(String, )
    conforme_15 = Column(Boolean, nullable=False)
    evaluacion_requisito_16 = Column(String, )
    conforme_16 = Column(Boolean, nullable=False)
    evaluacion_requisito_17 = Column(String, )
    conforme_17 = Column(Boolean, nullable=False)
    evaluacion_requisito_18 = Column(String, )
    conforme_18 = Column(Boolean, nullable=False)
    evaluacion_requisito_19 = Column(String, )
    conforme_19 = Column(Boolean, nullable=False)
    evaluacion_requisito_20 = Column(String, )
    conforme_20 = Column(Boolean, nullable=False)
    # trial820 = Column(String, )

class PA_PE_AU(Base):
    __tablename__ = 'pa_pe_au'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    autorizado_por = Column(String, )
    fecha = Column(DateTime, )
    autorizado_a = Column(String, )
    cargo = Column(String, )
    autorizacion_a = Column(String, )
    comentario = Column(String, )
    # trial820 = Column(String, )

class PA_PE_CV(Base):
    __tablename__ = 'pa_pe_cv'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    personal = Column(String, )
    requisito_de_competencia = Column(String, )
    carrera_curso_logro = Column(String, )
    institucion = Column(String, )
    fecha_inicio = Column(DateTime, )
    fecha_final = Column(DateTime, )
    carga_horaria = Column(Float, )
    descripción = Column(String, )
    respaldo = Column(String, )
    # trial820 = Column(String, )

class PA_PE_DE(Base):
    __tablename__ = 'pa_pe_de'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, nullable=False)
    cargo = Column(String, )
    abreviacion = Column(String, primary_key=True, nullable=False)
    # trial811 = Column(String, )

class PA_PE_EC(Base):
    __tablename__ = 'pa_pe_ec'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, nullable=False)
    elemento_de_competencia = Column(String, primary_key=True, nullable=False)
    # trial820 = Column(String, )

class PA_PE_EF(Base):
    __tablename__ = 'pa_pe_ef'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_plan = Column(Integer, )
    fecha = Column(DateTime, )
    participante_1 = Column(String, )
    participante_2 = Column(String, )
    participante_3 = Column(String, )
    participante_4 = Column(String, )
    participante_5 = Column(String, )
    participante_6 = Column(String, )
    participante_7 = Column(String, )
    participante_8 = Column(String, )
    participante_9 = Column(String, )
    participante_10 = Column(String, )
    comentarios_observaciones = Column(String, )
    actividad_evaluacion = Column(String, )
    conclusion_eficacia = Column(String, )
    eficaz = Column(Boolean, nullable=False)
    cerrado = Column(Boolean, nullable=False)
    # trial820 = Column(String, )

class PA_PE_FG(Base):
    __tablename__ = 'pa_pe_fg'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    forma_de_generacion = Column(String, )
    # trial820 = Column(String, )

class PA_PE_IE(Base):
    __tablename__ = 'pa_pe_ie'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_is = Column(Integer, )
    cargo = Column(String, )
    item = Column(String, )
    actividad = Column(String, )
    # trial820 = Column(String, )

class PA_PE_IS(Base):
    __tablename__ = 'pa_pe_is'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    cargo = Column(String, )
    item = Column(String, )
    comentarios = Column(String, )
    # trial820 = Column(String, )

class PA_PE_PE(Base):
    __tablename__ = 'pa_pe_pe'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, nullable=False)
    nombre = Column(String, nullable=False)
    abreviatura = Column(String, primary_key=True, nullable=False)
    cargo = Column(String, )
    fotografia = Column(String, )
    fecha_de_nacimiento = Column(DateTime, )
    direccion = Column(String, )
    telefono_personal = Column(String, )
    telefono_corporativo = Column(String, )
    movil_personal = Column(String, )
    movil_corporativo = Column(String, )
    email_personal = Column(String, )
    email_corporativo = Column(String, )
    nacionalidad = Column(String, )
    documento_de_identidad = Column(String, )
    estado_civil = Column(String, )
    categoria_de_licencia_de_conducir = Column(String, )
    vigente = Column(Boolean, nullable=False)
    descripcion = Column(String, )
    # trial814 = Column(String, )
    pa_eq_mo_items = relationship('PA_EQ_MO', back_populates='pa_pe_pe_rel')
    pc_es_es_items = relationship('PC_ES_ES', back_populates='pa_pe_pe_rel')

class PA_PE_PL(Base):
    __tablename__ = 'pa_pe_pl'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    item_del_programa = Column(Integer, )
    elaborado_por = Column(String, )
    fecha_inicio = Column(DateTime, )
    forma_generacion = Column(String, )
    responsable_de_generacion_de_competencia = Column(String, )
    tematica = Column(String, )
    asistentes = Column(String, )
    comentarios_de_la_generacion_de_competencia = Column(String, )
    evaluacion_si_aplica = Column('evaluacion-si_aplica', Float, )
    conclusion = Column(String, )
    respaldo1 = Column(String, )
    respaldo2 = Column(String, )
    respaldo3 = Column(String, )
    competencia = Column(Boolean, nullable=False)
    fecha_final = Column(DateTime, )
    # trial820 = Column(String, )

class PA_PE_PO(Base):
    __tablename__ = 'pa_pe_po'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    proceso_de_seleccion = Column(Integer, )
    postulante = Column(String, )
    educacion = Column(Float, )
    formacion = Column(Float, )
    experiencia = Column(Float, )
    habilidades = Column(Float, )
    conocimientotecnico = Column(Float, )
    calificacion = Column(Float, )
    resultado_cv = Column(Float, )
    pasa_a_entrevista = Column(Boolean, nullable=False)
    item_entrevista1 = Column(Float, )
    item_entrevista2 = Column(Float, )
    item_entrevista3 = Column(Float, )
    item_entrevista4 = Column(Float, )
    item_entrevista5 = Column(Float, )
    resultado_entrevista = Column(Float, )
    seleccionado = Column(Boolean, nullable=False)
    # trial820 = Column(String, )

class PA_PE_PR(Base):
    __tablename__ = 'pa_pe_pr'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    actividad = Column(String, )
    dirigido_a = Column(String, )
    competencia_por_adquirir = Column(String, )
    fecha_programada = Column(DateTime, )
    comentarios = Column(String, )
    # trial820 = Column(String, )

class PA_PE_RQ(Base):
    __tablename__ = 'pa_pe_rq'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    fecha = Column(DateTime, )
    responsable = Column(String, )
    cargo_req = Column(String, )
    educacion1 = Column(String, )
    educacion2 = Column(String, )
    educacion3 = Column(String, )
    formacion1 = Column(String, )
    formacion2 = Column(String, )
    formacion3 = Column(String, )
    formacion4 = Column(String, )
    formacion5 = Column(String, )
    formacion6 = Column(String, )
    formacion7 = Column(String, )
    formacion8 = Column(String, )
    formacion9 = Column(String, )
    formacion10 = Column(String, )
    experiencia1 = Column(String, )
    experiencia2 = Column(String, )
    experiencia3 = Column(String, )
    experiencia4 = Column(String, )
    experiencia5 = Column(String, )
    habilidades1 = Column(String, )
    habilidades2 = Column(String, )
    habilidades3 = Column(String, )
    habilidades4 = Column(String, )
    habilidades5 = Column(String, )
    habilidades6 = Column(String, )
    habilidades7 = Column(String, )
    habilidades8 = Column(String, )
    habilidades9 = Column(String, )
    habilidades10 = Column(String, )
    conocimiento1 = Column(String, )
    conocimiento2 = Column(String, )
    conocimiento3 = Column(String, )
    conocimiento4 = Column(String, )
    conocimiento5 = Column(String, )
    conocimiento6 = Column(String, )
    conocimiento7 = Column(String, )
    conocimiento8 = Column(String, )
    conocimiento9 = Column(String, )
    conocimiento10 = Column(String, )
    calificacion1 = Column(String, )
    calificacion2 = Column(String, )
    calificacion3 = Column(String, )
    calificacion4 = Column(String, )
    calificacion5 = Column(String, )
    aprobado_vigente = Column(Boolean, nullable=False)
    comentarios = Column(String, )
    educacion1c = Column(Boolean, nullable=False)
    educacion2c = Column(Boolean, nullable=False)
    educacion3c = Column(Boolean, nullable=False)
    formacion1c = Column(Boolean, nullable=False)
    formacion2c = Column(Boolean, nullable=False)
    formacion3c = Column(Boolean, nullable=False)
    formacion4c = Column(Boolean, nullable=False)
    formacion5c = Column(Boolean, nullable=False)
    formacion6c = Column(Boolean, nullable=False)
    formacion7c = Column(Boolean, nullable=False)
    formacion8c = Column(Boolean, nullable=False)
    formacion9c = Column(Boolean, nullable=False)
    formacion10c = Column(Boolean, nullable=False)
    experiencia1c = Column(Boolean, nullable=False)
    experiencia2c = Column(Boolean, nullable=False)
    experiencia3c = Column(Boolean, nullable=False)
    experiencia4c = Column(Boolean, nullable=False)
    experiencia5c = Column(Boolean, nullable=False)
    habilidades1c = Column(Boolean, nullable=False)
    habilidades2c = Column(Boolean, nullable=False)
    habilidades3c = Column(Boolean, nullable=False)
    habilidades4c = Column(Boolean, nullable=False)
    habilidades5c = Column(Boolean, nullable=False)
    habilidades6c = Column(Boolean, nullable=False)
    habilidades7c = Column(Boolean, nullable=False)
    habilidades8c = Column(Boolean, nullable=False)
    habilidades9c = Column(Boolean, nullable=False)
    habilidades10c = Column(Boolean, nullable=False)
    conocimiento1c = Column(Boolean, nullable=False)
    conocimiento2c = Column(Boolean, nullable=False)
    conocimiento3c = Column(Boolean, nullable=False)
    conocimiento4c = Column(Boolean, nullable=False)
    conocimiento5c = Column(Boolean, nullable=False)
    conocimiento6c = Column(Boolean, nullable=False)
    conocimiento7c = Column(Boolean, nullable=False)
    conocimiento8c = Column(Boolean, nullable=False)
    conocimiento9c = Column(Boolean, nullable=False)
    conocimiento10c = Column(Boolean, nullable=False)
    calificacion1c = Column(Boolean, nullable=False)
    calificacion2c = Column(Boolean, nullable=False)
    calificacion3c = Column(Boolean, nullable=False)
    calificacion4c = Column(Boolean, nullable=False)
    calificacion5c = Column(Boolean, nullable=False)
    # trial820 = Column(String, )

class PA_PE_SE(Base):
    __tablename__ = 'pa_pe_se'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    responsable = Column(String, )
    fecha = Column(DateTime, )
    personal = Column(String, )
    cargo = Column(String, )
    doc1 = Column(String, )
    doc2 = Column(String, )
    doc3 = Column(String, )
    doc4 = Column(String, )
    doc5 = Column(String, )
    requisitos = Column(Integer, )
    ev_educacion1 = Column(String, )
    cumple_educacion1 = Column(Boolean, nullable=False)
    ev_educacion2 = Column(String, )
    cumple_educacion2 = Column(Boolean, nullable=False)
    ev_educacion3 = Column(String, )
    cumple_educacion3 = Column(Boolean, nullable=False)
    ev_formacion1 = Column(String, )
    cumple_formacion1 = Column(Boolean, nullable=False)
    ev_formacion2 = Column(String, )
    cumple_formacion2 = Column(Boolean, nullable=False)
    ev_formacion3 = Column(String, )
    cumple_formacion3 = Column(Boolean, nullable=False)
    ev_formacion4 = Column(String, )
    cumple_formacion4 = Column(Boolean, nullable=False)
    ev_formacion5 = Column(String, )
    cumple_formacion5 = Column(Boolean, nullable=False)
    ev_formacion6 = Column(String, )
    cumple_formacion6 = Column(Boolean, nullable=False)
    ev_formacion7 = Column(String, )
    cumple_formacion7 = Column(Boolean, nullable=False)
    ev_formacion8 = Column(String, )
    cumple_formacion8 = Column(Boolean, nullable=False)
    ev_formacion9 = Column(String, )
    cumple_formacion9 = Column(Boolean, nullable=False)
    ev_formacion10 = Column(String, )
    cumple_formacion10 = Column(Boolean, nullable=False)
    ev_experiencia1 = Column(String, )
    cumple_experiencia1 = Column(Boolean, nullable=False)
    ev_experiencia2 = Column(String, )
    cumple_experiencia2 = Column(Boolean, nullable=False)
    ev_experiencia3 = Column(String, )
    cumple_experiencia3 = Column(Boolean, nullable=False)
    ev_experiencia4 = Column(String, )
    cumple_experiencia4 = Column(Boolean, nullable=False)
    ev_experiencia5 = Column(String, )
    cumple_experiencia5 = Column(Boolean, nullable=False)
    ev_habilidades1 = Column(String, )
    cumple_habilidades1 = Column(Boolean, nullable=False)
    ev_habilidades2 = Column(String, )
    cumple_habilidades2 = Column(Boolean, nullable=False)
    ev_habilidades3 = Column(String, )
    cumple_habilidades3 = Column(Boolean, nullable=False)
    ev_habilidades4 = Column(String, )
    cumple_habilidades4 = Column(Boolean, nullable=False)
    ev_habilidades5 = Column(String, )
    cumple_habilidades5 = Column(Boolean, nullable=False)
    ev_habilidades6 = Column(String, )
    cumple_habilidades6 = Column(Boolean, nullable=False)
    ev_habilidades7 = Column(String, )
    cumple_habilidades7 = Column(Boolean, nullable=False)
    ev_habilidades8 = Column(String, )
    cumple_habilidades8 = Column(Boolean, nullable=False)
    ev_habilidades9 = Column(String, )
    cumple_habilidades9 = Column(Boolean, nullable=False)
    ev_habilidades10 = Column(String, )
    cumple_habilidades10 = Column(Boolean, nullable=False)
    ev_conocimiento1 = Column(String, )
    cumple_conocimiento1 = Column(Boolean, nullable=False)
    ev_conocimiento2 = Column(String, )
    cumple_conocimiento2 = Column(Boolean, nullable=False)
    ev_conocimiento3 = Column(String, )
    cumple_conocimiento3 = Column(Boolean, nullable=False)
    ev_conocimiento4 = Column(String, )
    cumple_conocimiento4 = Column(Boolean, nullable=False)
    ev_conocimiento5 = Column(String, )
    cumple_conocimiento5 = Column(Boolean, nullable=False)
    ev_conocimiento6 = Column(String, )
    cumple_conocimiento6 = Column(Boolean, nullable=False)
    ev_conocimiento7 = Column(String, )
    cumple_conocimiento7 = Column(Boolean, nullable=False)
    ev_conocimiento8 = Column(String, )
    cumple_conocimiento8 = Column(Boolean, nullable=False)
    ev_conocimiento9 = Column(String, )
    cumple_conocimiento9 = Column(Boolean, nullable=False)
    ev_conocimiento10 = Column(String, )
    cumple_conocimiento10 = Column(Boolean, nullable=False)
    ev_calificacion1 = Column(String, )
    cumple_calificacion1 = Column(Boolean, nullable=False)
    ev_calificacion2 = Column(String, )
    cumple_calificacion2 = Column(Boolean, nullable=False)
    ev_calificacion3 = Column(String, )
    cumple_calificacion3 = Column(Boolean, nullable=False)
    ev_calificacion4 = Column(String, )
    cumple_calificacion4 = Column(Boolean, nullable=False)
    ev_calificacion5 = Column(String, )
    cumple_calificacion5 = Column(Boolean, nullable=False)
    conclusion = Column(String, )
    competencia_asegurada = Column(Boolean, nullable=False)
    educacion1 = Column(String, )
    educacion1c = Column(Boolean, nullable=False)
    educacion2 = Column(String, )
    educacion2c = Column(Boolean, nullable=False)
    educacion3 = Column(String, )
    educacion3c = Column(Boolean, nullable=False)
    formacion1 = Column(String, )
    formacion1c = Column(Boolean, nullable=False)
    formacion2 = Column(String, )
    formacion2c = Column(Boolean, nullable=False)
    formacion3 = Column(String, )
    formacion3c = Column(Boolean, nullable=False)
    formacion4 = Column(String, )
    formacion4c = Column(Boolean, nullable=False)
    formacion5 = Column(String, )
    formacion5c = Column(Boolean, nullable=False)
    formacion6 = Column(String, )
    formacion6c = Column(Boolean, nullable=False)
    formacion7 = Column(String, )
    formacion7c = Column(Boolean, nullable=False)
    formacion8 = Column(String, )
    formacion8c = Column(Boolean, nullable=False)
    formacion9 = Column(String, )
    formacion9c = Column(Boolean, nullable=False)
    formacion10 = Column(String, )
    formacion10c = Column(Boolean, nullable=False)
    experiencia1 = Column(String, )
    experiencia1c = Column(Boolean, nullable=False)
    experiencia2 = Column(String, )
    experiencia2c = Column(Boolean, nullable=False)
    experiencia3 = Column(String, )
    experiencia3c = Column(Boolean, nullable=False)
    experiencia4 = Column(String, )
    experiencia4c = Column(Boolean, nullable=False)
    experiencia5 = Column(String, )
    experiencia5c = Column(Boolean, nullable=False)
    habilidades1 = Column(String, )
    habilidades1c = Column(Boolean, nullable=False)
    habilidades2 = Column(String, )
    habilidades2c = Column(Boolean, nullable=False)
    habilidades3 = Column(String, )
    habilidades3c = Column(Boolean, nullable=False)
    habilidades4 = Column(String, )
    habilidades4c = Column(Boolean, nullable=False)
    habilidades5 = Column(String, )
    habilidades5c = Column(Boolean, nullable=False)
    habilidades6 = Column(String, )
    habilidades6c = Column(Boolean, nullable=False)
    habilidades7 = Column(String, )
    habilidades7c = Column(Boolean, nullable=False)
    habilidades8 = Column(String, )
    habilidades8c = Column(Boolean, nullable=False)
    habilidades9 = Column(String, )
    habilidades9c = Column(Boolean, nullable=False)
    habilidades10 = Column(String, )
    habilidades10c = Column(Boolean, nullable=False)
    conocimiento1 = Column(String, )
    conocimiento1c = Column(Boolean, nullable=False)
    conocimiento2 = Column(String, )
    conocimiento2c = Column(Boolean, nullable=False)
    conocimiento3 = Column(String, )
    conocimiento3c = Column(Boolean, nullable=False)
    conocimiento4 = Column(String, )
    conocimiento4c = Column(Boolean, nullable=False)
    conocimiento5 = Column(String, )
    conocimiento5c = Column(Boolean, nullable=False)
    conocimiento6 = Column(String, )
    conocimiento6c = Column(Boolean, nullable=False)
    conocimiento7 = Column(String, )
    conocimiento7c = Column(Boolean, nullable=False)
    conocimiento8 = Column(String, )
    conocimiento8c = Column(Boolean, nullable=False)
    conocimiento9 = Column(String, )
    conocimiento9c = Column(Boolean, nullable=False)
    conocimiento10 = Column(String, )
    conocimiento10c = Column(Boolean, nullable=False)
    calificacion1 = Column(String, )
    calificacion1c = Column(Boolean, nullable=False)
    calificacion2 = Column(String, )
    calificacion2c = Column(Boolean, nullable=False)
    calificacion3 = Column(String, )
    calificacion3c = Column(Boolean, nullable=False)
    calificacion4 = Column(String, )
    calificacion4c = Column(Boolean, nullable=False)
    calificacion5 = Column(String, )
    calificacion5c = Column(Boolean, nullable=False)
    educacion1n = Column(Integer, )
    educacion2n = Column(Integer, )
    educacion3n = Column(Integer, )
    formacion1n = Column(Integer, )
    formacion2n = Column(Integer, )
    formacion3n = Column(Integer, )
    formacion4n = Column(Integer, )
    formacion5n = Column(Integer, )
    formacion6n = Column(Integer, )
    formacion7n = Column(Integer, )
    formacion8n = Column(Integer, )
    formacion9n = Column(Integer, )
    formacion10n = Column(Integer, )
    experiencia1n = Column(Integer, )
    experiencia2n = Column(Integer, )
    experiencia3n = Column(Integer, )
    experiencia4n = Column(Integer, )
    experiencia5n = Column(Integer, )
    habilidades1n = Column(Integer, )
    habilidades2n = Column(Integer, )
    habilidades3n = Column(Integer, )
    habilidades4n = Column(Integer, )
    habilidades5n = Column(Integer, )
    habilidades6n = Column(Integer, )
    habilidades7n = Column(Integer, )
    habilidades8n = Column(Integer, )
    habilidades9n = Column(Integer, )
    habilidades10n = Column(Integer, )
    conocimiento1n = Column(Integer, )
    conocimiento2n = Column(Integer, )
    conocimiento3n = Column(Integer, )
    conocimiento4n = Column(Integer, )
    conocimiento5n = Column(Integer, )
    conocimiento6n = Column(Integer, )
    conocimiento7n = Column(Integer, )
    conocimiento8n = Column(Integer, )
    conocimiento9n = Column(Integer, )
    conocimiento10n = Column(Integer, )
    calificacion1n = Column(Integer, )
    calificacion2n = Column(Integer, )
    calificacion3n = Column(Integer, )
    calificacion4n = Column(Integer, )
    calificacion5n = Column(Integer, )
    promedio = Column(Integer, )
    escala = Column(Integer, )
    # trial820 = Column(String, )

class PA_PE_SP(Base):
    __tablename__ = 'pa_pe_sp'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    puesto = Column(String, )
    fecha_inicial = Column(DateTime, )
    evaluadores = Column(String, )
    ponderacion_educacion = Column(Float, )
    ponderacion_formacion = Column(Float, )
    ponderacion_habilidades = Column(Float, )
    ponderacion_experiencia = Column(Float, )
    ponderacion_conocimientotecnico = Column(Float, )
    ponderacion_calificacion = Column(Float, )
    ponderacion_minima_cv = Column(Float, )
    conclusion_cv = Column(String, )
    item_entrevista_1 = Column(String, )
    ponderacion_entrevista_1 = Column(Float, )
    item_entrevista_2 = Column(String, )
    ponderacion_entrevista_2 = Column(Float, )
    item_entrevista_3 = Column(String, )
    ponderacion_entrevista_3 = Column(Float, )
    item_entrevista_4 = Column(String, )
    ponderacion_entrevista_4 = Column(Float, )
    item_entrevista_5 = Column(String, )
    ponderacion_entrevista_5 = Column(Float, )
    ponderacion_minima_entrevista = Column(Float, )
    conclusion_entrevista = Column(String, )
    fecha_final = Column(DateTime, )
    # trial820 = Column(String, )

class PA_PE_SU(Base):
    __tablename__ = 'pa_pe_su'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    fecha = Column(DateTime, )
    supervisores = Column(String, )
    supervisados = Column(String, )
    item_de_supervision_1 = Column(String, )
    supervision_exitosa_1 = Column(Boolean, nullable=False)
    item_de_supervision_2 = Column(String, )
    supervision_exitosa_2 = Column(Boolean, nullable=False)
    item_de_supervision_3 = Column(String, )
    supervision_exitosa_3 = Column(Boolean, nullable=False)
    item_de_supervision_4 = Column(String, )
    supervision_exitosa_4 = Column(Boolean, nullable=False)
    item_de_supervision_5 = Column(String, )
    supervision_exitosa_5 = Column(Boolean, nullable=False)
    item_de_supervision_6 = Column(String, )
    supervision_exitosa_6 = Column(Boolean, nullable=False)
    item_de_supervision_7 = Column(String, )
    supervision_exitosa_7 = Column(Boolean, nullable=False)
    item_de_supervision_8 = Column(String, )
    supervision_exitosa_8 = Column(Boolean, nullable=False)
    item_de_supervision_9 = Column(String, )
    supervision_exitosa_9 = Column(Boolean, nullable=False)
    item_de_supervision_10 = Column(String, )
    supervision_exitosa_10 = Column(Boolean, nullable=False)
    comentarios = Column(String, )
    requiere_adquirir_o_aumentar_competencia = Column(Boolean, nullable=False)
    cargo = Column(String, )
    item = Column(String, )
    # trial820 = Column(String, )

class PA_PE_TP(Base):
    __tablename__ = 'pa_pe_tp'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    nombre = Column(String, )
    cargo = Column(String, )
    parametro_a_evaluar = Column(Integer, )
    codigo_material = Column(Integer, )
    valor_de_referencia = Column(Integer, )
    valor_medido = Column(Integer, )
    incertidumbre = Column(Integer, )
    incertidumbre_muestra = Column(Integer, )
    dispersión = Column(Integer, )
    z = Column(Integer, )
    evaluador = Column(String, )
    cargo_evaluador = Column(String, )
    fecha = Column(DateTime, )
    comentarios_dispersión = Column(String, )
    # trial824 = Column(String, )

class PA_PS_AD(Base):
    __tablename__ = 'pa_ps_ad'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    producto_o_servicio = Column(String, )
    proveedor_seleccionado = Column(Integer, )
    precio_unitario = Column(Float, )
    cantidad = Column(Float, )
    recursos_requeridos_bs = Column(Float, )
    doc_1 = Column(String, )
    doc_2 = Column(String, )
    comunicacion_1 = Column(String, )
    comunicacion_2 = Column(String, )
    fecha_recepción = Column(DateTime, )
    observaciones = Column(String, )
    id_requisitos_de_productos_y_servicios = Column(Integer, )
    especificacion_1 = Column(String, )
    comentario_esp_1 = Column(String, )
    cumple_esp_1 = Column(Boolean, nullable=False)
    especificacion_2 = Column(String, )
    comentario_esp_2 = Column(String, )
    cumple_esp_2 = Column(Boolean, nullable=False)
    especificacion_3 = Column(String, )
    comentario_esp_3 = Column(String, )
    cumple_esp_3 = Column(Boolean, nullable=False)
    especificacion_4 = Column(String, )
    comentario_esp_4 = Column(String, )
    cumple_esp_4 = Column(Boolean, nullable=False)
    especificacion_5 = Column(String, )
    comentario_esp_5 = Column(String, )
    cumple_esp_5 = Column(Boolean, nullable=False)
    conclusión_evaluación = Column(String, )
    reclamo_u_observación_al_proveedor = Column(String, )
    doc_3 = Column(String, )
    doc_4 = Column(String, )
    retroalimentacion_realizada = Column(Boolean, nullable=False)
    retroalimentacion = Column(String, )
    cerrado_eficazmente = Column(Boolean, nullable=False)
    # trial814 = Column(String, )
    pa_ps_ev_items = relationship('PA_PS_EV', back_populates='pa_ps_ad_rel')
    pa_ps_os_items = relationship('PA_PS_OS', back_populates='pa_ps_ad_rel')

class PA_PS_CR(Base):
    __tablename__ = 'pa_ps_cr'
    __table_args__ = {'schema': 'SGApp'}
    id_criterio = Column(Integer, primary_key=True, nullable=False)
    criterio = Column(String, )
    categoria = Column(String, )
    ponderacion = Column(Float, )
    # trial824 = Column(String, )
    pa_ps_de_items = relationship('PA_PS_DE', back_populates='pa_ps_cr_rel')

class PA_PS_DE(Base):
    __tablename__ = 'pa_ps_de'
    __table_args__ = {'schema': 'SGApp'}
    id_detalle = Column(Integer, primary_key=True, nullable=False)
    id_evaluacion = Column(Integer, )
    id_criterio = Column(Integer, ForeignKey('SGApp.pa_ps_cr.id_criterio'))
    puntuacion = Column(Integer, )
    # trial824 = Column(String, )
    pa_ps_cr_rel = relationship('PA_PS_CR', back_populates='pa_ps_de_items')

class PA_PS_EV(Base):
    __tablename__ = 'pa_ps_ev'
    __table_args__ = {'schema': 'SGApp'}
    id_evaluacion = Column(Integer, primary_key=True, nullable=False)
    id_proveedor = Column(Integer, )
    id_adquisicion = Column(Integer, ForeignKey('SGApp.pa_ps_ad.id'))
    id_productoservicio = Column(Integer, )
    fecha_evaluacion = Column(DateTime, )
    tipo_evaluacion = Column(String, )
    puntaje_final = Column(Float, )
    calificacion_final = Column(String, )
    observacion_general = Column(String, )
    # trial824 = Column(String, )
    pa_ps_ad_rel = relationship('PA_PS_AD', back_populates='pa_ps_ev_items')

class PA_PS_OS(Base):
    __tablename__ = 'pa_ps_os'
    __table_args__ = {'schema': 'SGApp'}
    id_os = Column(Integer, primary_key=True, nullable=False)
    id_ad = Column(Integer, ForeignKey('SGApp.pa_ps_ad.id'))
    descripcion = Column(String, )
    cantidad = Column(Float, )
    precio_unitario = Column(Float, )
    importe = Column(Float, )
    # trial824 = Column(String, )
    pa_ps_ad_rel = relationship('PA_PS_AD', back_populates='pa_ps_os_items')

class PA_PS_PR(Base):
    __tablename__ = 'pa_ps_pr'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, nullable=False)
    proveedor = Column(String, primary_key=True, nullable=False)
    razon_social = Column(String, )
    nit = Column(String, )
    dirección = Column(String, )
    teléfono_celular = Column(String, )
    correo_electrónico = Column(String, )
    persona_de_contacto = Column(String, )
    comentario_observación = Column(String, )
    doc_prov_1 = Column(String, )
    doc_prov_2 = Column(String, )
    doc_prov_3 = Column(String, )
    # trial824 = Column(String, )

class PA_PS_PS(Base):
    __tablename__ = 'pa_ps_ps'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    producto_servicio = Column(String, nullable=False)
    comentario = Column(String, )
    rango_valor_nominal = Column(String, )
    resolución_o_clase = Column(String, )
    contenedor_estuche = Column(String, )
    accesorios = Column(String, )
    especificacion_1 = Column(String, )
    especificacion_2 = Column(String, )
    especificacion_3 = Column(String, )
    especificacion_4 = Column(String, )
    especificacion_5 = Column(String, )
    observaciones = Column(String, )
    adjunto1 = Column(String, )
    adjunto2 = Column(String, )
    adjunto3 = Column(String, )
    vigente = Column(Boolean, nullable=False)
    # trial814 = Column(String, )

class PC_ES_ES(Base):
    __tablename__ = 'pc_es_es'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    responsable = Column(String, ForeignKey('SGApp.pa_pe_pe.abreviatura'))
    fecha = Column(DateTime, )
    ensayo = Column(String, )
    tipo_de_sr = Column(String, )
    a = Column(Float, )
    b = Column(Float, )
    c = Column(Float, )
    d = Column(Float, )
    rr = Column(Float, )
    rrv = Column(Float, )
    srrv = Column(Float, )
    rrp3 = Column(Float, )
    rrp2 = Column(Float, )
    rrl3 = Column(Float, )
    rrl2 = Column(Float, )
    vigente = Column(Boolean, nullable=False)
    comentarios = Column(String, )
    mr = Column(String, )
    rre = Column(Float, )
    balanza = Column(String, )
    termohigrometro = Column(String, )
    tli = Column(Float, )
    hli = Column(Float, )
    tlf = Column(Float, )
    hlf = Column(Float, )
    ti = Column(Float, )
    hi = Column(Float, )
    tf = Column(Float, )
    hf = Column(Float, )
    delta_t = Column(Float, )
    delta_h = Column(Float, )
    aceptado_t = Column(String, )
    aceptado_h = Column(String, )
    # trial824 = Column(String, )
    pa_pe_pe_rel = relationship('PA_PE_PE', back_populates='pc_es_es_items')

class PC_LAB_PATRONES(Base):
    __tablename__ = 'pc_lab_patrones'
    __table_args__ = {'schema': 'SGApp'}
    codigo_patron = Column(String, primary_key=True, nullable=False)
    descripcion = Column(String, )
    valor_verdadero = Column(Float, )
    incertidumbre = Column(Float, )
    # trial824 = Column(String, )

class PC_LAB_SOLUCIONES(Base):
    __tablename__ = 'pc_lab_soluciones'
    __table_args__ = {'schema': 'SGApp'}
    id_solucion = Column(Integer, primary_key=True, nullable=False)
    nombre_solucion = Column(String, )
    lote_interno = Column(String, )
    fecha_preparacion = Column(DateTime, )
    fecha_vencimiento = Column(DateTime, )
    normalidad_teorica = Column(Float, )
    factor_correcion = Column(Float, )
    estado = Column(String, )
    peso_equivalente_patron = Column(Float, )
    rsd_obtenido = Column(Float, )
    # trial824 = Column(String, )

class PC_LAB_SOLUCIONES_DET(Base):
    __tablename__ = 'pc_lab_soluciones_det'
    __table_args__ = {'schema': 'SGApp'}
    id_replica = Column(Integer, primary_key=True, nullable=False)
    id_solucion = Column(Integer, )
    masa_patron = Column(Float, )
    volumen_gasto = Column(Float, )
    factor_calculado = Column(Float, )
    # trial824 = Column(String, )

class PC_LAB_VALIDACIONMETODOS(Base):
    __tablename__ = 'pc_lab_validacionmetodos'
    __table_args__ = {'schema': 'SGApp'}
    id_metodo = Column(Integer, primary_key=True, nullable=False)
    nombre_metodo = Column(String, )
    limite_cuantificacion = Column(Float, )
    limite_deteccion = Column(Float, )
    decimales_reporte = Column(Integer, )
    modelo_repetibilidad = Column(String, )
    coef_a = Column(Float, )
    coef_b = Column(Float, )
    coef_c = Column(Float, )
    limite_sesgo = Column(Float, )
    # trial824 = Column(String, )

class PC_QR_QU(Base):
    __tablename__ = 'pc_qr_qu'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    codigo_servicio = Column(String, )
    contacto = Column(String, )
    descripción = Column(String, )
    recibido_vía = Column(String, )
    procede = Column(Boolean, nullable=False)
    evaluacion_entrevistas = Column(String, )
    acciones_a_tomar = Column(String, )
    comunicación_tratamiento = Column(String, )
    medio_tratamiento = Column(String, )
    comunicación_cierre = Column(String, )
    medio_cierre = Column(String, )
    queja_cerrada = Column(Boolean, nullable=False)
    seguimiento_por = Column(String, )
    comunicado_por = Column(String, )
    queja_con_probabilidad_de_que_se_repita = Column(Boolean, nullable=False)
    # trial824 = Column(String, )

class PC_RE_AC(Base):
    __tablename__ = 'pc_re_ac'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_y_recepcionado_por = Column(String, )
    fecha_de_registro = Column(DateTime, )
    n_registro = Column(String, )
    proforma = Column(Integer, )
    cliente = Column(Integer, )
    direccion = Column(String, )
    ciudad = Column(String, )
    pais = Column(String, )
    contacto = Column(Integer, )
    celular = Column(String, )
    e_mail = Column('e-mail', String, )
    personal = Column(Boolean, nullable=False)
    inst_cond_amb = Column(Boolean, nullable=False)
    equipamiento = Column(Boolean, nullable=False)
    metodo = Column(Boolean, nullable=False)
    tiempo_capacidad = Column(Boolean, nullable=False)
    comentarios_de_recursos = Column(String, )
    responsable_de_muestra = Column(String, )
    nro_de_muestras = Column(Integer, )
    insertar_muestras = Column(Boolean, nullable=False)
    servicio_global = Column(Integer, )
    todos_global = Column(Boolean, nullable=False)
    enviar_global = Column(Boolean, nullable=False)
    servicio = Column(Integer, )
    todos = Column(Boolean, nullable=False)
    enviar = Column(Boolean, nullable=False)
    fecha_de_recepcion = Column(DateTime, )
    dias_de_entrega = Column(Integer, )
    fecha_estimada_de_entrega = Column(DateTime, )
    entregado_por = Column(String, )
    ot = Column(String, )
    registro_ot = Column(String, )
    numero_de_muestras = Column(Integer, )
    fecha_de_entrega_a_ensayo = Column(DateTime, )
    fecha_de_entrega_de_resultados_al_area = Column(DateTime, )
    fecha_de_descarte_de_la_muestra = Column(DateTime, )
    fecha_de_inicio_del_analisis = Column(DateTime, )
    fecha_de_entrega_de_los_resultados = Column(DateTime, )
    analista_responsable = Column(String, )
    tipo_de_muestra = Column(String, )
    producto = Column(String, )
    marca = Column(String, )
    cantidad = Column(String, )
    tipo_de_envase = Column(String, )
    vencimiento = Column(String, )
    caracteristicas = Column(String, )
    tipo_de_muestra_todos = Column(Boolean, nullable=False)
    producto_todos = Column(Boolean, nullable=False)
    marca_todos = Column(Boolean, nullable=False)
    cantidad_todos = Column(Boolean, nullable=False)
    tipo_de_envase_todos = Column(Boolean, nullable=False)
    vencimiento_todos = Column(Boolean, nullable=False)
    caracteristicas_todos = Column(Boolean, nullable=False)
    tipo_de_muestra_enviar = Column(Boolean, nullable=False)
    producto_enviar = Column(Boolean, nullable=False)
    marca_enviar = Column(Boolean, nullable=False)
    cantidad_enviar = Column(Boolean, nullable=False)
    tipo_de_envase_enviar = Column(Boolean, nullable=False)
    vencimiento_enviar = Column(Boolean, nullable=False)
    caracteristicas_enviar = Column(Boolean, nullable=False)
    # trial824 = Column(String, )

class PC_RE_ANALISIS(Base):
    __tablename__ = 'pc_re_analisis'
    __table_args__ = {'schema': 'SGApp'}
    id_analisis = Column(Integer, primary_key=True, nullable=False)
    id_ac = Column(Integer, )
    id_muestra = Column(Integer, )
    codigo_muestra = Column(String, )
    ensayo_solicitado = Column(String, )
    metodo_nombre = Column(String, )
    unidades_reporte = Column(String, )
    estado = Column(String, )
    fecha_analisis = Column(DateTime, )
    analista = Column(String, )
    tipo_registro = Column(String, )
    referencia_qa = Column(String, )
    id_termohigrometro = Column(String, )
    temp_ini = Column(Float, )
    hum_ini = Column(Float, )
    temp_fin = Column(Float, )
    hum_fin = Column(Float, )
    id_balanza = Column(String, )
    id_bureta = Column(String, )
    id_solucion = Column(Integer, )
    r1_masa_lectura = Column(Float, )
    r1_masa_real = Column(Float, )
    r1_vol_lectura = Column(Float, )
    r1_vol_real = Column(Float, )
    r2_masa_lectura = Column(Float, )
    r2_masa_real = Column(Float, )
    r2_vol_lectura = Column(Float, )
    r2_vol_real = Column(Float, )
    r3_masa_lectura = Column(Float, )
    r3_masa_real = Column(Float, )
    r3_vol_lectura = Column(Float, )
    r3_vol_real = Column(Float, )
    factor11 = Column(Float, )
    factor12 = Column(Float, )
    factor13 = Column(Float, )
    factor14 = Column(Float, )
    factor15 = Column(Float, )
    resultado_promedio = Column(Float, )
    desviacion_s = Column(Float, )
    resultado_final_reporte = Column(String, )
    conformidad = Column(String, )
    factor11_real = Column(Float, )
    factor12_real = Column(Float, )
    factor13_real = Column(Float, )
    factor14_real = Column(Float, )
    factor15_real = Column(Float, )
    # trial827 = Column(String, )

class PC_RE_CC(Base):
    __tablename__ = 'pc_re_cc'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_cl = Column(Integer, )
    contacto = Column(String, )
    celular = Column(String, )
    e_mail = Column('e-mail', String, )
    # trial824 = Column(String, )

class PC_RE_CL(Base):
    __tablename__ = 'pc_re_cl'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    cliente = Column(String, )
    nit = Column(String, )
    direccion = Column(String, )
    ciudad = Column(String, )
    pais = Column(String, )
    telefono = Column(String, )
    e_mail = Column('e-mail', String, )
    # trial824 = Column(String, )

class PC_RE_CO(Base):
    __tablename__ = 'pc_re_co'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    fecha = Column(DateTime, )
    revisado_por = Column(String, )
    informacion_por_revisar = Column(String, )
    revision = Column(String, )
    informacion_revisada = Column(String, )
    # trial827 = Column(String, )

class PC_RE_MU(Base):
    __tablename__ = 'pc_re_mu'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_ac = Column(Integer, )
    codigo = Column(String, )
    tipo_de_muestra = Column(String, )
    producto = Column(String, )
    marca = Column(String, )
    cantidad = Column(String, )
    tipo_de_envase = Column(String, )
    vencimiento = Column(String, )
    caracteristicas = Column(String, )
    ensayo01 = Column(String, )
    unidades01 = Column(String, )
    metodo01 = Column(String, )
    ensayo02 = Column(String, )
    unidades02 = Column(String, )
    metodo02 = Column(String, )
    ensayo03 = Column(String, )
    unidades03 = Column(String, )
    metodo03 = Column(String, )
    ensayo04 = Column(String, )
    unidades04 = Column(String, )
    metodo04 = Column(String, )
    ensayo05 = Column(String, )
    unidades05 = Column(String, )
    metodo05 = Column(String, )
    ensayo06 = Column(String, )
    unidades06 = Column(String, )
    metodo06 = Column(String, )
    ensayo07 = Column(String, )
    unidades07 = Column(String, )
    metodo07 = Column(String, )
    ensayo08 = Column(String, )
    unidades08 = Column(String, )
    metodo08 = Column(String, )
    ensayo09 = Column(String, )
    unidades09 = Column(String, )
    metodo09 = Column(String, )
    ensayo10 = Column(String, )
    unidades10 = Column(String, )
    metodo10 = Column(String, )
    ensayo11 = Column(String, )
    unidades11 = Column(String, )
    metodo11 = Column(String, )
    ensayo12 = Column(String, )
    unidades12 = Column(String, )
    metodo12 = Column(String, )
    ensayo13 = Column(String, )
    unidades13 = Column(String, )
    metodo13 = Column(String, )
    ensayo14 = Column(String, )
    unidades14 = Column(String, )
    metodo14 = Column(String, )
    ensayo15 = Column(String, )
    unidades15 = Column(String, )
    metodo15 = Column(String, )
    ensayo16 = Column(String, )
    unidades16 = Column(String, )
    metodo16 = Column(String, )
    ensayo17 = Column(String, )
    unidades17 = Column(String, )
    metodo17 = Column(String, )
    ensayo18 = Column(String, )
    unidades18 = Column(String, )
    metodo18 = Column(String, )
    ensayo19 = Column(String, )
    unidades19 = Column(String, )
    metodo19 = Column(String, )
    ensayo20 = Column(String, )
    unidades20 = Column(String, )
    metodo20 = Column(String, )
    ensayo21 = Column(String, )
    unidades21 = Column(String, )
    metodo21 = Column(String, )
    ensayo22 = Column(String, )
    unidades22 = Column(String, )
    metodo22 = Column(String, )
    ensayo23 = Column(String, )
    unidades23 = Column(String, )
    metodo23 = Column(String, )
    ensayo24 = Column(String, )
    unidades24 = Column(String, )
    metodo24 = Column(String, )
    ensayo25 = Column(String, )
    unidades25 = Column(String, )
    metodo25 = Column(String, )
    cod_cliente = Column(String, )
    # trial827 = Column(String, )

class PC_RE_OF(Base):
    __tablename__ = 'pc_re_of'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    fecha = Column(DateTime, )
    revisado_por = Column(String, )
    informacion_por_revisar = Column(String, )
    revision = Column(String, )
    informacion_revisada = Column(String, )
    # trial827 = Column(String, )

class PC_RE_PI(Base):
    __tablename__ = 'pc_re_pi'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_pr = Column(Integer, )
    tipo_de_muestra = Column(String, )
    servicio = Column(Integer, )
    metodo = Column(String, )
    precio = Column(Float, )
    cantidad = Column(Integer, )
    precio_total = Column(Float, )
    # trial827 = Column(String, )

class PC_RE_PR(Base):
    __tablename__ = 'pc_re_pr'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    area = Column(String, )
    registro = Column(String, )
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    hora = Column(DateTime, )
    cliente = Column(String, )
    solicitante = Column(String, )
    subtotal = Column(Float, )
    nro_muestras = Column(Integer, )
    porcentaje_de_descuento = Column(Float, )
    descuento = Column(Float, )
    total_a_cancelar = Column(Float, )
    tiempo_de_entrega = Column(Integer, )
    comentarios_observaciones = Column(String, )
    factura = Column(String, )
    fecha_de_factura = Column(DateTime, )
    forma_de_pago = Column(String, )
    pago = Column(String, )
    valido_hasta = Column(DateTime, )
    cantidad_minima_requerida = Column(String, )
    condiciones_de_la_muestra = Column(String, )
    # trial824 = Column(String, )

class PC_RE_SE(Base):
    __tablename__ = 'pc_re_se'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    area = Column(String, )
    servicio = Column(String, )
    metodo = Column(String, )
    unidades = Column(String, )
    precio = Column(Float, )
    comentario = Column(String, )
    # trial824 = Column(String, )

class PC_RE_SG(Base):
    __tablename__ = 'pc_re_sg'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    servicio_global = Column(String, )
    area = Column(String, )
    # trial824 = Column(String, )

class PC_RE_SH(Base):
    __tablename__ = 'pc_re_sh'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_sg = Column(Integer, )
    servicio = Column(Integer, )
    # trial827 = Column(String, )

class PC_RE_SO(Base):
    __tablename__ = 'pc_re_so'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    fecha = Column(DateTime, )
    revisado_por = Column(String, )
    informacion_por_revisar = Column(String, )
    revision = Column(String, )
    informacion_revisada = Column(String, )
    # trial827 = Column(String, )

class PC_TC_TC(Base):
    __tablename__ = 'pc_tc_tc'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    area_de_tnc = Column(String, )
    servicio = Column(String, )
    descripcion = Column(String, )
    detencion = Column(Boolean, nullable=False)
    retencion_de_informes = Column(Boolean, nullable=False)
    porque = Column(String, )
    tipo_de_tnc = Column(String, )
    accion = Column(String, )
    responsable_de_reanudacion_del_trabajo = Column(String, )
    autorizacion_de_reanudacion = Column(Boolean, nullable=False)
    se_puede_repetir = Column(Boolean, nullable=False)
    repetición_del_tnc = Column(Boolean, nullable=False)
    abrir_otro_tnc = Column(Boolean, nullable=False)
    comunicacion_al_cliente = Column(Boolean, nullable=False)
    comunicacion_realizada_al_cliente = Column(String, )
    decision_del_cliente = Column(String, )
    el_trabajo_se_acepta = Column(Boolean, nullable=False)
    anulacion_del_trabajo = Column(Boolean, nullable=False)
    requiere_accion_correctiva = Column(Boolean, nullable=False)
    observaciones = Column(String, )
    cierre_tcnc = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_PL_AC(Base):
    __tablename__ = 'pe_pl_ac'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    riesgo_oportunidad = Column(Integer, nullable=False)
    correciones = Column(Integer, )
    acciones_correctivas = Column(Integer, )
    acciones_de_mejora = Column(Integer, )
    acciones_abordar = Column(String, )
    responsable_actividades = Column(String, )
    recursos = Column(String, )
    fecha_frecuencia_actividad = Column(DateTime, )
    resultado_esperado = Column(String, )
    fecha_seguimiento = Column(DateTime, )
    responsable_seguimiento = Column(String, )
    probabilidadrev = Column(Integer, )
    impactorev = Column(Integer, )
    valorrev = Column(Integer, )
    conclusión_seguimiento = Column(String, )
    realizado = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_PL_CO(Base):
    __tablename__ = 'pe_pl_co'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    contexto = Column(String, )
    tipo = Column(String, )
    descripción = Column(String, )
    vigente = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_PL_ES(Base):
    __tablename__ = 'pe_pl_es'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    contexto_interno = Column(Integer, )
    contexto_externo = Column(Integer, )
    estrategia = Column(String, )
    comentario = Column(String, )
    vigente = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_PL_OB(Base):
    __tablename__ = 'pe_pl_ob'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    estrategia_1 = Column(Integer, )
    estrategia_2 = Column(Integer, )
    estrategia_3 = Column(Integer, )
    estrategia_4 = Column(Integer, )
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    objetivo = Column(String, nullable=False)
    indicador = Column(String, )
    meta = Column(String, )
    tiempo = Column(String, )
    propietario = Column(String, )
    vigente = Column(Boolean, nullable=False)
    comentarios = Column(String, )
    # trial827 = Column(String, )

class PE_PL_PC(Base):
    __tablename__ = 'pe_pl_pc'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    responsable = Column(String, )
    fecha = Column(DateTime, )
    riesgo_oportunidad = Column(Integer, nullable=False)
    actividad_contingecia = Column(String, )
    responsable_contingencia = Column(String, )
    vigente = Column(Boolean, nullable=False)
    comentario = Column(String, )
    # trial827 = Column(String, )

class PE_PL_PI(Base):
    __tablename__ = 'pe_pl_pi'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    tipo = Column(String, )
    parte_interesada = Column(String, )
    requisito1 = Column(String, )
    requisito2 = Column(String, )
    requisito3 = Column(String, )
    requisito4 = Column(String, )
    descripcion_de_la_relacion = Column(String, )
    vigente = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_PL_PL(Base):
    __tablename__ = 'pe_pl_pl'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    objetivo = Column(Integer, )
    actividad = Column(String, )
    recursos = Column(String, )
    plazo = Column(DateTime, )
    resultado_esperado = Column(String, )
    responsable_seguimiento = Column(String, )
    comentarios_observaciones = Column(String, )
    cumplido = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_PL_RO(Base):
    __tablename__ = 'pe_pl_ro'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    actividad_de_planificacion = Column(Integer, )
    registrado_por = Column(String, )
    fecha = Column(DateTime, )
    evento = Column(String, )
    consecuencia = Column(String, )
    riesgo_oportunidad = Column(String, )
    ctrl_existente = Column(String, )
    probabilidad = Column(Integer, )
    impacto = Column(Integer, )
    valor_de_riesgo = Column(Integer, )
    comentario = Column(String, )
    vigente = Column(Boolean, nullable=False)
    abordaje = Column(Boolean, nullable=False)
    probabilidad_rev = Column(Integer, )
    impacto_rev = Column(Integer, )
    valor_de_riesgo_rev = Column(Integer, )
    eficacia_de_acciones = Column(String, )
    conclusion_de_seguimiento = Column(String, )
    # trial827 = Column(String, )

class PE_SE_AC(Base):
    __tablename__ = 'pe_se_ac'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    fecha_registro = Column(DateTime, )
    registrado_por = Column(String, )
    descripcion_de_la_no_conformidad = Column(String, )
    evidencia = Column(String, )
    requisito_o_criterio_implicado = Column(String, )
    analisis_de_la_no_conformidad = Column(String, )
    por_qu_1 = Column(String, )
    por_qu_2 = Column(String, )
    por_qu_3 = Column(String, )
    por_qu_4 = Column(String, )
    por_qu_5 = Column(String, )
    no_conformidad_similar_o_potencial = Column(String, )
    causa = Column(String, )
    responsable_de_seguimiento = Column(String, )
    fecha_de_seguimiento_de_eficacia_de_acciones = Column(DateTime, )
    efecto_deseado = Column(String, )
    seguimiento = Column(String, )
    eficaz = Column(Boolean, nullable=False)
    fecha_seguimiento = Column(DateTime, )
    observaciones = Column(String, )
    cerrado = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_SE_CA(Base):
    __tablename__ = 'pe_se_ca'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    acciones_correctivas = Column(Integer, )
    acciones_abordar = Column(String, )
    responsable_actividades = Column(String, )
    recursos = Column(String, )
    fecha_frecuencia_actividad = Column(DateTime, )
    resultado_esperado = Column(String, )
    fecha_seguimiento = Column(DateTime, )
    responsable_seguimiento = Column(String, )
    conclusión_seguimiento = Column(String, )
    realizado = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_SE_CO(Base):
    __tablename__ = 'pe_se_co'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    correcciones = Column(Integer, )
    acciones_abordar = Column(String, )
    responsable_actividades = Column(String, )
    recursos = Column(String, )
    fecha_frecuencia_actividad = Column(DateTime, )
    resultado_esperado = Column(String, )
    fecha_seguimiento = Column(DateTime, )
    responsable_seguimiento = Column(String, )
    conclusión_seguimiento = Column(String, )
    realizado = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_SE_EE(Base):
    __tablename__ = 'pe_se_ee'
    __table_args__ = {'schema': 'SGApp'}
    entradas = Column(String, primary_key=True)
    # trial827 = Column(String, )

class PE_SE_EN(Base):
    __tablename__ = 'pe_se_en'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_re = Column(Integer, )
    entrada = Column(String, )
    fuente = Column(String, )
    link = Column(String, )
    conveniencia = Column(String, )
    conveniente = Column(Boolean, nullable=False)
    adecuación = Column(String, )
    adecuado = Column(Boolean, nullable=False)
    eficacia = Column(String, )
    eficaz = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_SE_MA(Base):
    __tablename__ = 'pe_se_ma'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    acciones_de_mejora = Column(Integer, )
    acciones_abordar = Column(String, )
    responsable_actividades = Column(String, )
    recursos = Column(String, )
    fecha_frecuencia_actividad = Column(DateTime, )
    resultado_esperado = Column(String, )
    fecha_seguimiento = Column(DateTime, )
    responsable_seguimiento = Column(String, )
    conclusión_seguimiento = Column(String, )
    realizado = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_SE_ME(Base):
    __tablename__ = 'pe_se_me'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    fecha_registro = Column(DateTime, )
    registrado_por = Column(String, )
    oportunidad_de_mejora = Column(String, )
    descripcion_de_oportunidad_de_mejora = Column(String, )
    analisis_de_la_oportunidad_de_mejora = Column(String, )
    oportunidad_de_mejora_seleccionada = Column(Boolean, nullable=False)
    responsable_de_seguimiento = Column(String, )
    fecha_de_seguimiento_de_eficacia_de_acciones = Column(DateTime, )
    efecto_deseado = Column(String, )
    seguimiento = Column(String, )
    eficaz = Column(Boolean, nullable=False)
    fecha_seguimiento = Column(DateTime, )
    observaciones = Column(String, )
    cerrado = Column(Boolean, nullable=False)
    # trial827 = Column(String, )

class PE_SE_RE(Base):
    __tablename__ = 'pe_se_re'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    participante_1 = Column(String, )
    participante_2 = Column(String, )
    participante_3 = Column(String, )
    participante_4 = Column(String, )
    participante_5 = Column(String, )
    participante_6 = Column(String, )
    participante_7 = Column(String, )
    participante_8 = Column(String, )
    fecha = Column(DateTime, )
    medio_de_reunión = Column(String, )
    tipo_de_revisión = Column(String, )
    comentarios_y_observaciones = Column(String, )
    # trial827 = Column(String, )

class PE_SE_SA(Base):
    __tablename__ = 'pe_se_sa'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    id_re = Column(Integer, )
    salida = Column(String, )
    decisión = Column(String, )
    acciones = Column(String, )
    # trial827 = Column(String, )

class PE_SE_SS(Base):
    __tablename__ = 'pe_se_ss'
    __table_args__ = {'schema': 'SGApp'}
    salidas = Column(String, primary_key=True)
    # trial827 = Column(String, )

class SYS_FACTORESK(Base):
    __tablename__ = 'sys_factoresk'
    __table_args__ = {'schema': 'SGApp'}
    id = Column(Integer, primary_key=True, nullable=False)
    descripcion = Column(String, )
    factor = Column(Float, )
    # trial830 = Column(String, )

class TBL_LUGARES(Base):
    __tablename__ = 'tbl_lugares'
    __table_args__ = {'schema': 'SGApp'}
    lugarid = Column(Integer, primary_key=True, nullable=False)
    ciudad = Column(String, )
    departamento = Column(String, )
    altitud = Column(Integer, )
    presionref_hpa = Column(Integer, )
    humedadref_pct = Column(Integer, )
    prioridad = Column(Integer, )
    # trial830 = Column(String, )

class TBL_POSICIONES_HORNO(Base):
    __tablename__ = 'tbl_posiciones_horno'
    __table_args__ = {'schema': 'SGApp'}
    posicionid = Column(Integer, primary_key=True, nullable=False)
    clasedeequipo = Column(String, )
    nombreposicion = Column(String, )
    # trial830 = Column(String, )

